version: "3.7"

services:
  django:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    command: gunicorn core.wsgi:application -b :8000 -b :80 --reload
    volumes:
      - ./src/backend:/app
      - ./src/frontend/build:/frontend:cached
    ports:
      - 8000:8000
      - 80:80
    stdin_open: true
    tty: true

  builder:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    command: npm run dev
    environment:
      - HOST=0.0.0.0
    ports:
      - 3000:3000
    volumes:
      - ./src/frontend:/app:cached
      - /app/node_modules
    depends_on:
      - django

volumes:
  myapp:


